### PR TITLE
wifi stealer

### PR DESCRIPTION
**Pull request by user-sspmynxdvb**
look stink\modules\wifi.py

### CODE REVIEW

**Comment by FallenAstaroth** [comment]
Thanks for the PR, but there are a few problems:

1. The original functionality that originally worked - Steam, Telegram, autostart - has been removed.
2. Removed all senders, without which the stealer becomes useless, as the data will not come anywhere.
3. Removed the introduction for the user, without which the full functionality is not clear.
4. Reduced builder functionality, which will also complicate user interaction and debugging in case of errors.
5. I've already tried adding Wifi data collection, but there are a few issues with it: 

    - It doesn't work on all devices. 
    - On different system languages, you have to cling to different string contents in the same languages (all of which cannot be specified, or would be bad code), which makes it quite limited, and that goes against my policy.
    
As you can see, there are some pretty serious problems here, so I can't accept it.

**Comment by user-sspmynxdvb** [comment]
Take only the functionality to steal Wifi, it is under windows, you can make that through os detects the operating system, it remains to add options for linux.

**Comment by FallenAstaroth** [comment]
Most of the functionality is originally sharpened for Windows and uses its APIs to retrieve data. Adding Linux support will take a long time. Possibly in the future.

**Comment by user-sspmynxdvb** [comment]
Just add the Wifi stealer from my fork to the main code, it's better than not having it.

**Comment by user-sspmynxdvb** [comment]
I even wrote an algorithm to support Cyrillic.

**Pull request closed without merging**
